version: "3.6"

services:

  iris:
    container_name: snext-iris
    build:
      context: .
      dockerfile: Dockerfile
    #image: store/intersystems/iris-community:2019.2.0.107.0
    volumes:
     - "./samples:/durable/samples/"
     - "./license:/durable/license/"
    environment:
      #- ISC_DATA_DIRECTORY=/durable
      - TZ=Europe/Paris
    ports:
     - "9092:52773"
     - "9091:51773"
    command: --password-file /durable/password/password.txt 
    
##    version: "3.2"

##services:

##  traefik:
##    image:  traefik:v2.0
##    command: --api.insecure=true --providers.docker
##    expose:
##       - "80"
##       - "8080" 
    
##    volumes:
##       - "/var/run/docker.sock:/var/run/docker.sock:ro"

    
