version: "3.6"

services:
  swagger:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports:
      - "9093:8080"
  iris:
    container_name: snext-iris
    build:
      context: .
      dockerfile: Dockerfile
    #image: store/intersystems/iris-community:2019.2.0.107.0
    #volumes:
    # - "./iris-password:/durable/password/"
    #environment:
     # - ISC_DATA_DIRECTORY=/durable
    ports:
     - "9092:52773"
     - "9091:51773"
    command: --password-file /durable/password/password.txt
