version: "3.6"

services:

  iris:
    container_name: snext-iris
    build:
      context: .
      dockerfile: Dockerfile
    #image: store/intersystems/iris-community:2019.2.0.107.0
    volumes:
     - "./samples:/durable/samples/"
     - "./license:/durable/license/"
    environment:
      #- ISC_DATA_DIRECTORY=/durable
      - TZ=Europe/Paris
    ports:
     - "9092:52773"
     - "9091:51773"
    command: --password-file /durable/password/password.txt 
