Class snext.docdb.serviceParameters Extends %DocDB.Document [ Owner = {irisowner}, ProcedureBlock ]
{
	
Storage Default
{
<Data name="%Doc">
<Attribute>%Doc</Attribute>
<Structure>node</Structure>
<Subscript>"%Doc"</Subscript>
</Data>
<Data name="serviceParametersDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>%LastModified</Value>
</Value>
</Data>
<DataLocation>^Bv5P.BhKE.1</DataLocation>
<DefaultData>serviceParametersDefaultData</DefaultData>
<ExtentLocation>^Bv5P.BhKE</ExtentLocation>
<IdLocation>^Bv5P.BhKE.1</IdLocation>
<Index name="IDKEY">
<Location>^Bv5P.BhKE.1</Location>
</Index>
<IndexLocation>^Bv5P.BhKE.I</IndexLocation>
<StreamLocation>^Bv5P.BhKE.S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
