Class snext.masterdata.scn.Edge Extends %Persistent [ Abstract ]
{

Storage Default
{
<Data name="EdgeDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^snext.masterdata.scn.EdgeD</DataLocation>
<DefaultData>EdgeDefaultData</DefaultData>
<IdLocation>^snext.masterdata.scn.EdgeD</IdLocation>
<IndexLocation>^snext.masterdata.scn.EdgeI</IndexLocation>
<StreamLocation>^snext.masterdata.scn.EdgeS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
